# Literature Review

  Overview

This chapter reviews the existing academic and practical field research related to the development and observed effectiveness of temporary portable rumble strips (TPRS). It reviews research regarding the impact of TPRS on driving behavior, including the reducing reduction of erratic driving and excessive speed, the increasing increase of driver awareness, and the reduction of crashes. It reviews what conclusions from past research has concluded about the cost-benefit analyses of TPRS and reviews existing research about the tendency of TPRS to become displaced from prolonged exposure to oncoming traffic. The chapter then proceeds to review specifications for the spacing of TPRS layouts developed by both manufacturers and state transportation agencies. It concludes with a very brief discussion on the possibilities of exploring the effect various spacing layouts may have on the effectiveness of TPRS, particularly as it pertains to the findings of prior research. 

  Effectiveness of Temporary Portable Rumble Strips 

TPRS have been in use since at least the early 2000s (Meyer, 2000). The earliest TPRS products were peel-and-stick adhesive tapes, whose installation required dry weather, mild to warm temperatures, and clean roads (Myers Industries, 2021). Early testing found the tape to be too thin to impact driver behavior (Meyer, 2000) and was therefore often installed in two layers (Fontaine and Carlson, 2001; Maze, 2000). Non-adhesive TPRS products made of steel and rubber quickly entered the market in 2009 (Meyer et al., 2006; PSS, 2018), thick enough to create sufficient auditory feedback (Schrock et al., 2010) and heavy enough to remain in place (Shrock et al., 2016; Sun et al., 2011). Studies generally show that TPRS minimize lane departures (Brown et al., 2022; Sun et al., 2011; Wang et al., 2013), reduce traffic speed (Brown et al., 2022; Sun et al., 2011; Wang et al., 2013; Yang et al., 2015), increase compliance with posted speed limits (Brown et al., 2022; Yang et al., 2015), increase driver attentiveness (Brown et al., 2022; Sun et al., 2011; Wang et al., 2013; Yang et al., 2015), and reduce crash rates (Ullman et al., 2018), all with sufficient effectiveness to justify their cost (Brown et al., 2022). However, a limiting factor on the effectiveness of TPRS which has not been as thoroughly or frequently explored by prior research is the tendency of TPRS, particularly non-adhesive strips, to shift overtime and become displaced in their positions from traversing traffic (Heaslip et al., 2010; Schrock, 2016; Sun et al., 2011). Additionally, there is limited understanding as to what degree this shifting and displacement influences the effectiveness of TPRS. While the latest literature suggests positive cost-to-benefit ratios, these studies provide limited insight into how TPRS displaces under traffic loads and no evaluation of the increased safety risk of having workers adjust the strips during the workday. The following subsections will discuss why non-adhesive TPRS were developed, the effectiveness of TPRS to influence various errant driver behaviors and reduce crash rates, displacement of TPRS under traffic loads, and a summary of the observed effectiveness of TPRS and the remaining questions that provide opportunities for additional research.  

 Product Development – Adhesive Strips to Portable Plastic 

At the end of the 1990s, the Kansas Department of Transportation (DOT) sought an alternative to cold-mix asphalt rumble strips it used to alert drivers to upcoming work zones; Kansas DOT desired strips that were faster to install and remove, while still alerting drivers effectively. This interest prompted over a decade of product development and study on TPRS. The first products available were peel-and-stick adhesive tapes around 1/8 in thick placed in multi-strip arrays. Adhesive TPRS was found to be too thin to make a noticeable impact (i.e., noise) on vehicles passing over the strips (Maze, 2000; Meyer, 2000). Any difference in driver behavior was attributed to the bright orange color of the adhesive TPRS, and it was speculated that thicker strips with different spacing would create stronger audible and tactile feedback to drivers (Meyer, 2000). Increased strip thickness, initially achieved by stacking the strips on top of one another, did create more noise within vehicles and slow drivers down (Fontaine and Carlson, 2001), but the need for fair weather, a clean road surface, and reapplication of adhesive limited the application and lifespan of adhesive tapes (Brown et al., 2022; Myers Industries, 2021). Meyer et al. (2006) developed specifications for a non-adhesive rumble strip, providing a solution for those limitations. In December 2008, Plastic Safety Systems (PSS) released the RoadQuake, a non-adhesive strip 3/4 in thick, made of rubber and steel (Plastic Safety Systems, 2018). Studies using both closed-course and field tests demonstrated that RoadQuake and similar non-adhesive TPRS created more noise feedback than adhesive TPRS and stayed in place when installed properly (Schrock et al., 2010; Schrock et al., 2016; Sun et al., 2011). Research on adhesive TPRS since the development of non-adhesive TPRS is lacking, indicating a strong industry shift. Unless stated otherwise, all mentions of TPRS in the remainder of this report refer to the non-adhesive variety. 

 Lane Departures and Erratic Driving 

Early research into the impacts of TPRS focus on the threat of motorists evading TPRS arrays and thereby creating dangerous traffic safety situations by departing from their lane and entering the adjacent lane. These studies (Sun et al., 2011; Wang et al., 2013) report minimal evasion, and recent work (Brown et al., 2022) suggests that this behavior has further decreased over time. 

Sun et al. (2011) observed higher lane departures on two-way, two-lane roads with narrower lanes, on a bridge, and during flagging operations. They suggested that narrow lanes may motivate partial lane departures and recommend placing TPRS across the full width of the road in situations where two-way traffic is funneled through a single lane. This eliminates the ability to avoid TPRS by swerving with minimal impacts for traffic in the opposite direction. 

Wang et al. (2013) focused on two-way, two-lane roads and observed fewer lane departures as the oncoming traffic volume increased. This study shows that lane departures increase when TPRS appear on a downhill slope. Furthermore, nearly all lane departures occur at the final set of TPRS, after the drivers have already encountered one or two sets and were closer to the flagger at the start of the work zone. Wang et al. (2013) did not give additional context to their findings, so a specific cause for avoiding the final set of TPRS cannot be determined from the study. It may be that drivers are successfully alerted to the work zone and are either prematurely following instructions from the flagger to change lanes or simply avoiding the discomfort of traveling over the rumble strips.  

Brown et al. (2022) observed one vehicle out of 8,000 – a motorcycle – evade the TPRS. This low evasion rate implied that lane departures are rare, but also suggested that motorcyclists may feel increased risk when passing over TPRS. The authors did not specify whether the motorcycle was swerving around 1/8 in adhesive TPRS or 3/4 in non-adhesive TPRS, nor under what conditions of traffic or time of day. Although Heaslip et al. (2010) discusses the increased risk motorcyclists may encounter with TPRS, most studies either do not mention motorcycles or explicitly exclude them (Wang et al., 2013). 

At least for cars and trucks, it appears that lane departures are a minimal concern. Lane departures may be further mitigated by improved signage warning of TPRS and better layout designs, but further research would be necessary.  

 Speed Reductions 

Systems with TPRS installations decrease average driving speed and increase compliance with posted speed limits. Studies with TPRS installed show speed reductions ranging from 3.5 mph to 13.8 mph, and around a 20 percent increase in compliance with posted speed limits (Brown et al., 2022; Fontaine and Carlson, 2001; Sun et al., 2011; Wang et al., 2013; Yang et al., 2015). The impact of TPRS is highly localized (Shahin et al., 2023), with more limited speed reduction further away from the worksite (McAvoy et al., 2009). As soon as drivers are past the first set of TPRS or other traffic calming devices, they have been observed to accelerate unless they can see an additional barrier such as a flagger or another set of TPRS (Wang et al., 2013). Cars moving faster than other traffic, such as speeding vehicles or those driving in the left lane, slow down more than slower moving vehicles (Wang et al., 2013; Yang et al., 2015). These findings all come from real world tests on two-way, two-lane roads except for Shahin et al. (2023) which was based on a driving simulator of a divided highway.  

Brown et al. (2022) studied roads in Missouri, testing both divided highways and two-way two-lane roads with adhesive and non-adhesive TPRS. Their results suggest that adhesive strips are better than non-adhesive strips at slowing down traffic, but that non-adhesive strips are better than adhesive strips at improving compliance with posted speed limits. Missouri DOT used adhesive TPRS more frequently than non-adhesive TPRS at the time of the study and the comparison between adhesive and non-adhesive TPRS was not statistically conclusive, which may explain the seeming contradiction. The current literature agrees that non-adhesive TPRS does work to slow down traffic, but to what degree and how different layouts impact its effectiveness is only starting to be fully understood.  

 Increased Driver Awareness 

TPRS has been shown to improve driver awareness, observed by tracking how many vehicles trigger their brake lights when approaching TPRS. Studies agree that drivers hit their brakes more often and earlier when TPRS is present, but they disagree on how many drivers this affects, with observations ranging from 11 percent to 55 percent (Brown et al., 2022; Sun et al., 2011; Wang et al., 2013; Yang et al., 2015). By looking at each study’s tested work site, a few factors may be inferred.  

First, the type of vehicle may correlate with how attentive the driver is. Commercial trucks are generally more cautious and will brake sooner than most personal vehicles (Wang et al., 2013).  

Drivers also tend to slow down most at the first set of TPRS. Either the driver sees the TPRS coming and slows down in advance or is alerted to the altered traffic pattern as they travel over the first array of TPRS and slow down to appropriate speed before traveling over subsequent arrays (Wang et al., 2013).  

Where TPRS is placed relative to the work zone and how far ahead a driver can see both affect how much they slow down for TPRS. Strips placed too far away from the work site have little to no lasting impact on driving speed (McAvoy et al., 2009), with an exception for curved roads without line of sight to the work zone, where TPRS did slow drivers (Wang et al., 2013). It may be more accurate to claim that when drivers can clearly see that the work site is further away, they will not slow down for TPRS. That is, it is possible drivers are slowing for the work zone rather than for the TPRS. 

Brown et al. (2022), attempted to compare non-adhesive TPRS to adhesive TPRS on both divided highways and two-way, two-lane roads. Non-adhesive TPRS was found to be far more effective at getting drivers’ attention than adhesive strips, 52 percent compared to 6 percent, respectively. The same study recognized that the TPRS was brightly colored and used in connection with a flagger during a nighttime operation, a situation where drivers may already be on alert thus falsely exaggerating the impact of TPRS. In all situations, TPRS seems to get drivers’ attention, but to what degree and how their application influences their effectiveness varies by study. 

 Crash Reduction and Cost-to-Benefit Ratios 

 TPRS is reported to greatly reduce both the frequency of crashes as well as the severity of the crashes that do occur. Given that vehicle crashes are infrequent events, most studies have not evaluated the crash reduction factor directly, and instead evaluated indirect safety measures such as speed reduction (e.g., Yang et al. 2015). An exception is Ullman et al. (2018), who used historical crash data and compared the expected number of crashes with the actual number of crashes. The authors focused specifically on the I-35 expansions in Texas from 2012 to 2016, when Texas DOT widened I-35 to 6 lanes. They found that TPRS alone, when traffic was queued, reduced the number of crashes by 60 percent and of those crashes, the chance of serious injury was reduced from 50 percent to 16 percent (Ullman et al., 2018). The presence of queued traffic is significant, where for in non-queued traffic, TPRS only reduced crashes by 11 percent and did not have a significant impact on the severity of the crashes that did occur (Ullman et al., 2018). The 11 percent crash reduction was not shown to be statistically significant. The analysis was 98 percent confident when traffic was queued and crashes were reduced 60 percent, but only 23 percent confident with unqueued traffic where the crash reducing effect of TPRS was minimal (Ullman et al., 2018). It is important to note that these results are from a divided, multi-lane freeway.  

Brown et al. (2022) found TPRS to have a cost-to-benefit ratio ranging from 8.6 to 26.3, depending on traffic volume and how many TPRS were installed. Though showing very positive ratios in favor of using TPRS, these calculations made a few assumptions and did not include all possible costs related to using TPRS. First, the authors assumed that the crash-reducing effect of TPRS on a divided highway applied equally to adhesive strips and two-way, two-lane roads. Second, the authors used the much less certain, albeit much more conservative, 11 percent crash reduction rate from Ullman et al. (2018). If the more certain and more effective crash reduction rate of 60 percent associated with queued traffic is used in the analysis from Brown et al. (2022), the cost-to-benefit ratio increases from 8.6 to 47.1. Third, the authors considered only the initial purchase price of both TPRS and adhesive strips as well as the labor costs needed to install and remove the strips. Missing from this analysis is the time required to retrieve and re-adjust displaced strips, which can be substantial on some roads as discussed previously. Depending on traffic levels, waiting for gaps in traffic could require a significant amount of time adding to labor costs. The movement of TPRS under traffic is reportedly minimal (Sun et al., 2011), but there is anecdotal reference to damage done to the strips when dragged by trucks or strips lifting from the road surface and damaging the front of subsequent vehicles (Brown et al., 2022). All these factors could reduce the estimated cost-to-benefit ratio.  

Most of the studies examined pair TPRS with flagging operations where two-way traffic must be stopped and funneled into a single lane, thus creating queues. Using the queued crash reduction rate from Ullman et al. (2018) may be an accurate assumption despite the dissimilar road-types. More research is needed to evaluate the true costs and benefits of installing TPRS. 

 Displacement of Non-Adhesive Rumble Strips 

Non-adhesive rumble strips, such as Plastic Safety Systems’s RoadQuake product, depend on their weight and friction with the road surface to stay in place, rather than adhesives or fasteners (Plastic Safety Systems, 2018). Such a design should be expected to shift under traffic, but only a few studies attempt to quantify the slip of these products under a given traffic load. Further, the rate of displacement may be related to the condition of the strip, with worn and damaged strips displacing more than new strips. No known research to this point evaluates how quickly these products degrade under a given traffic load and at what point the strips cease to be effective at staying in place.  

Heaslip et al. (2010) showed that the weight of the vehicle, the speed of travel, and the number of passes over the strip have a positive linear trend with how much a particular strip will slide over time. The authors do not specify what brand of non-adhesive TPRS they were testing, nor do they provide specifications for the exact weight or dimensions of the product tested, so the magnitude of displacement they observed cannot be related to other products. Their testing used a closed course with a commercial truck, a sedan, and a motorcycle at different speeds with measurements taken after every pass for a total of 30 passes per vehicle per speed. Schrock et al. (2016) showed a similar positive relationship between weight, speed and displacement, also on a closed course using the RoadQuake and TrafFix rumble strips. Sun et al. (2011) is the only study that observed real-world use of the RoadQuake and tracked its rate of displacement, on a site with a posted work zone speed limit of 40 mph and low traffic volumes. Over the total observation period of almost 12 hours across 2 days, only 850 cars passed through the work zone. This study does not provide insights into how well RoadQuake works at higher speeds and higher volumes, and the authors did not collect enough data to correlate vehicle weight to rate of displacement, but did show that the strips slide less when they stay perpendicular to the direction of travel. This aligns with reports received from UDOT engineers saying that once strips start to rotate away from perpendicular, the strips will rotate and slide more with each impact (D. Monroe, personal communication, November 26, 2024). 

Schrock et al. (2016) is the only study found that investigated how identified products (i.e., RoadQuake and TrafFix) move when hit at higher traffic speeds. The author concluded that the RoadQuake stayed in place long enough to be used on roads with speeds up to 67.5 mph and an Annual Average Daily Traffic (AADT) of 3,000 vehicles/day, where the TrafFix product was only suitable for the lowest speeds and volumes on their scale. This study used a closed course and attempted to extrapolate 40 passes with a dump truck and sedan to a target AADT. This extrapolation asserted a linear relationship between vehicle impacts and rate of movement in TPRS, which might not be the cause as Sun et al. (2011) observed that TPRS placed at an angle to the traffic flow moved more per vehicle impact than TPRS placed perpendicular to the direction of travel. This suggests a non-linear relationship between vehicle impacts and TPRS movement and could compromise the Schrock et al. (2016) conclusion that the RoadQuake is adequate for freeway use. Schrock et al. (2016) also assumed that the strips could be adjusted every 4 hours over the workday. This places workers at a higher risk; changing that assumption to 9 hours would lead to a different conclusion that RoadQuake may not be suitable for higher speeds and volumes.   

The research team did not identify any studies that considered the age or condition of the TPRS before and after use, which could be a possible factor in their rate of displacement. The manufacturer of these non-adhesive strips says the product has a shelf-life of 3-5 years and offers a 3-year limited warranty (Plastic Safety Systems, 2024a), but they don’t report an expected lifespan under typical or heavy use. A study of effectiveness as a function of wear would be useful but would require tracking where and when individual strips have been and how many vehicles passed over them and at what speeds. 

 Summary of Observed Effectiveness of TPRS 

TPRS systems, and particularly TPRS, show positive trends towards slowing traffic and improving work zone safety. To what degree TPRS and adhesive strips improve safety is unclear as different studies show different levels of effectiveness depending on local driver awareness of TPRS and layout in coordination with other safety treatments. The relationship between these different factors and the effectiveness of TPRS requires greater examination. More research is also needed to observe the actual rate of displacement of TPRS under high-volume, high-speed traffic in a real-world setting. No research has been found concerning the ideal spacing between individual strips within an array and how spacing effects driver behavior or rate of displacement, so spacing on TPRS also requires additional research. 

## Citations and Bibliographies

Quarto has a robust method for generating citations. 
If you follow the [setup instructions](https://quarto.org/docs/visual-editor/technical.html#citations-from-zotero), 
then you can easily search your database from inside Rstudio after typing the `@` command. 
Keep your Zotero database up-to-date and correct (and share it with your coauthors!) to minimize the pain you will feel in writing articles.

Note that there are two ways to make citations. 
Doing `@key` will give you a text citation, allowing you to refer to the author mid-sentence.

> @ben-akivaDiscreteChoiceAnalysis1985 is the canonical reference in choice modeling for transportation.

But if you put the citation in brackets like `[@citationkey]` you can make parenthetical citations. 
You can also give page numbers for quotes or specific findings this way.

> The difference in the choice model logsum can be used as a measure of consumer surplus, and therefore accessibility improvement [@ben-akivaDiscreteChoiceAnalysis1985, p. 301].
