## Results and Analysis


```{r setup, file = "R/chapter_start.R", include = FALSE}
# a number of commands need to run at the beginning of each chapter. This
# includes loading libraries that I always use, as well as options for 
# displaying numbers and text.
library(modelsummary)
```

### Speeds
Analysis question 1: does having rumble strips slow down traffic?

```{r wavetronix}
# join observation information to the wavetonix data
tar_load(wavetronix)
tar_load(observations)

wavetronix <- wavetronix |>
  left_join(observations, by = c("site", "date")) 

```

```{r wgrp}
wavetronix |>
  group_by(site, strip_spacing, unit) |>
  summarise(speed_85 = mean(speed_85))
```

This is a t-test of means for one road comparing 35 ft spacing with no rumble strips.
```{r wtt}
groups <- wavetronix |>
  group_by(site, unit, strip_spacing) |> 
  select(speed_85) |>
  nest(-site, -unit, -strip_spacing) 

t.test(groups$data[[5]], groups$data[[7]])
t.test(groups$data[[9]], groups$data[[10]])
```




```{r wlm}
# estimate a model of the effect of rumble strips on speed
wlms <- wavetronix |>
  group_by(site) |>
  nest(data = -site) |>
  mutate(
    model = map(data, ~lm(speed_85 ~ unit, data = .x))
  )

list <- wlms$model |> setNames(wlms$site)
```


```{r}
modelsummary(list,  stars = TRUE)
```


## Braking and Avoidance

```{r}
tar_load(brake_and_departure)
brake_and_departure <- brake_and_departure |>
  mutate(
    departure = ifelse(departure == "Avoided", 1, 0),
    class = factor(class, levels = c("Motorcycle", "Passenger", "Truck")),
    class = fct_relevel(class, "Motorcycle", after = Inf) # move motorcycle to the end
  )
avoidance_model <- glm(departure ~ class + spacing_type + site, 
  data = brake_and_departure, family = binomial)

avoidance_sites <- brake_and_departure |>
  group_by(site) |>
  nest(data = -site) |>
  mutate(
    model = map(data, ~glm(departure ~ class + spacing_type, data = .x, family = binomial))
  )

# append all model 
list(avoidance_model, avoidance_sites$model) |>
  setNames(c("Pooled", avoidance_sites$site))
```


### Worker Exposure

```{r cdf-sites}

tar_load(cdf_plots)

cdf_plots$site_plot
```