# Discussion and Limitations
There was no consistent relationship between driver speed and the presence or absence of TPRS, and there was no consistent relationship between driver speeds and the spacing of strips TPRS array. This is contrary to the consensus of the studies discussed in Chapter 2, which found TPRS generally slows driving speeds by 3-13 mph. There are several hypothetical explanations for this observed discrepancy. One explanation is that Utah drivers behave differently with respect to TPRS than drivers in the states previously studied. Another is that TPRS technology is more mature now than when first studied; it may be that drivers have become accustomed to TPRS and previous studies observed drivers reacting to a novel technology. 

Other explanations for the discrepancy between this study’s findings and previous studies in the literature could be based in the methodology used for this research. The observed change in speed between sites was larger than the variance within a site, implying that other variables related to the site may have had a greater impact on drivers’ speed than the TPRS treatment. Curves in the road, traffic conditions on any given day, and sight lines from the TPRS array to the work zone could all be factors affecting driver speed. It was not possible for this study to control for these variables as they were endogenous to the site; more sites would need to be observed to control for these elements. The study used commercial radar speed detection units available from UDOT; these units provide only average and 85th percentile speeds within 15-minute time intervals. It may be that TPRS slow only the fastest 15 percent of drivers, a beneficial effect that this study could not have observed. The location of the second radar device was inconsistent between sites and observation days, potentially impacting the speed reduction measured here. An ideal location to measure final speed would be at the lane closure, but space was not available at the work sites to place this collection device at that point. A third speed measurement device could also have allowed the researchers to measure the speed of vehicles ahead of TPRS, providing more information on their effectiveness.

Finally, the primary design of TPRS as a traffic control device is to gain the attention of potentially inattentive drivers, with a reduction in speed as a potential consequence. Although change in speed is a common proxy measure for TPRS effectiveness, it would be better to observe driver attention directly. Prior studies have observed this effect by instrumenting the interior of cars with drivers in a closed and controlled setting; this would be difficult to do in field research. 

In terms of braking response, most drivers were not observed to activate their brake lights at any point as they traversed the TPRS. Of the drivers this study observed activating their brake lights, more did so before striking the TPRS than after. Braking behavior varied more across sites than within sites, indicating strong site-specific effects.

There are multiple interpretations of these findings. If the purpose of TPRS is to gain the attention of distracted drivers, then the fact that more drivers brake before TPRS – with visual warning rather than tactile warning – may suggest that visual cues are more influential tactile cues. On the other hand, the fact that some drivers are observed braking after TPRS suggests that for that small number of drivers, TPRS may have played a tactile role in alerting the driver of an upcoming work zone.

A primary limitation to observing brake lights was the difficulty in detecting activated brake lights and the limited observation window before the vehicle encountered TPRS. Some vehicles kept rear-facing tail lights illuminated similar to daytime running lights, relying on an increase in brightness to signal braking. Some brake light housings reflected the sunlight, making it difficult to see whether brake lights were illuminated. Both factors made it difficult to discern activated brake lights from false positives. To mitigate this, Camera 1 was placed closer to the TPRS array to see the vehicles in more detail. However, placing the camera closer shortened the amount of time vehicles were observed before striking the TPRS. Before the TPRS, vehicles were in frame for around 1-2 seconds or less, depending on the speed of traffic. After the TPRS, vehicles were in frame for 3 or more seconds. It is possible that some drivers braked before entering the field of view of Camera 1. The count of vehicles that activated their brake lights after the TPRS is likely more accurate than the counts of vehicles that braked before or not at all. Additional research is needed where a camera is placed farther upstream of the TPRS where drivers first see TPRS. Such footage would provide better insight into how drivers react to TPRS before striking them.

Most drivers in passenger vehicles and trucks do not leave their lane to avoid the TPRS, but a large portion of motorcycle drivers do. Drivers of all vehicle types appeared to avoid the TPRS in a manner similar to passing a slow-moving vehicle; that is, this study did not observe abrupt or sudden evasive maneuvers. The low rates of lane departure amongst drivers of passenger vehicles and trucks suggest that the increased risk of related collisions due to TPRS is low, but additional research would be needed to measure this effect.

TPRS move and displace during operation. The middle strip in a three-strip array appears to displace the most relative to the first and third strips. The amount of displacement was not affected by the spacing between the strips, and there is not a strong relationship between displacement and cumulative traffic momentum. Displacement was more correlated with the site. This could be a function of roadway geometry, pavement condition, or the condition of the strips themselves. All observed sites had asphalt surfaces, but this study did not measure pavement roughness or other specific characteristics that could have explained variation in displacement. This study also did not measure the level of wear of the individual TPRS or their age. Based on the strip designs used at these work zones, it is possible that some strips are more than 10 years old. Additionally, the assumptions made to calculate the cumulative momentum for TPRS displacement are very limited in their precision. While this is the first study to measure TPRS displacement in the field under live traffic loads, additional research is needed to correlate strip age and wear with displacement as well as refine methods to normalize traffic load on TPRS between sites.

Workers enter live traffic streams to correct the installation of displaced strips. This study measured that workers seek headway times in traffic of approximately 34 seconds in order to make these corrections. At all of the sites observed in this research, such a headway was observed at least 20 percent of the time. It may be that at roads with more traffic and therefore smaller headways, workers will accept shorter headways and take more risks. The necessary headway of 34 seconds is calculated from only six observed correction events; more observations may yield a more precise measure.

# Conclusion
The findings of this research suggest that driver responses to TPRS and the performance of the TPRS themselves are highly variable and strongly dependent on site-specific conditions rather than layout spacing, traffic speeds, or traffic volumes. Changes in vehicle speed showed no consistent relationship with the varied spacing of the TPRS layouts. Likely influences on speed data include uncontrolled differences across work zones and limitations in the setup and equipment used in the field research. Braking and avoidance behaviors were similarly inconsistent and difficult to interpret due to challenges in detecting brake activation and limited visibility. The data suggests that only a minority of drivers respond to TPRS, and of those that do most brake on the approach. Strip displacement also varies widely by site and does not correlate with spacing or estimated traffic momentum, suggesting influence from factors not observed in this study such as pavement condition, age and condition of the individual TPRS devices, and limitations in the method used to estimate momentum. While sufficient headways were present at the observed work zones, the results for worker exposure were based on only six instances when workers were observed to enter the roadway to adjust the TPRS. These limitations underscore the potential of future research implementing more precise measurements, expanded site sampling, and improved methods for assessing driver attention, braking, and TPRS condition.
