project:
  type: book

# This defines the .qmd files that are in your document
book:
  title: "Effectiveness of Temporary Portable Rumble Strips in Utah"
  author:
    - name: Gregory S. Macfarlane
      orcid: 0000-0003-3999-7584
      email: gregmacfarlane@byu.edu
      affiliations:
        - id: byu
          name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          postal-code: 84602
    # to add additional authors, simply add another -name: tag 
    - name: Tyler Carruth
      affiliations:
        - ref: byu
    - name: Benjamin Hailstone
      affiliations:
        - ref: byu
    - name: Grant G. Schultz
      orcid: 0000-0002-0675-2970
      affiliations:
        - ref: byu
  date: "8/1/2026"
  chapters:
    - index.qmd
    - 03_methods.qmd
    - 04_results.qmd
    - 05_conclusion.qmd
    - references.qmd
  abstract: |
    Transportation agencies regularly use Temporary portable rumble strips (TPRS) to alert 
    drivers to upcoming work zones or other changing traffic conditions, based on previous research
    showing TPRS to effectively reduce traffic speed and increase driver attentiveness.
    However, questions persist regarding the continued effectiveness of TPRS as drivers become accustomed to them,
    the preferred spacing of TPRS, and the need for workers to periodically enter the roadway and
    adjust the TPRS when they become displaced.
    This research presents the results of a field experiment at four sites in Utah with varying
    deployment conditions and TPRS spacings. The sites were instrumented with radar speed detectors and video cameras
    to capture change in speed, braking behavior, avoidance, strip displacement, and worker exposure.
    Results indicate that the effect of TPRS on speed reduction is inconclusive. Drivers who braked in response
    to TPRS typically did so before reaching the devices, suggesting that visual
    cues may be as influential as tactile feedback for most drivers. Avoidance behavior was
    common among motorcycles and occurred occasionally among other vehicles.
    Driver responses were more strongly influenced by site-specific factors—such
    as roadway geometry and sight distance—than by TPRS spacing. TPRS
    displacement occurred gradually under traffic but was not clearly related to
    traffic volume or speed, suggesting that device condition play a
    larger role. Maintenance requires traffic gaps of approximately 34 seconds,
    which may not be feasible at higher-volume sites. These findings highlight
    the need for further evaluation of TPRS effectiveness, standards for device
    condition, consideration of alternative measures for long-term work zones,
    and increased contractor discretion based on site conditions.
acknowledgements: |
    This research was funded by the Utah Department of Transportation 
    The authors alone are responsible for the preparation and accuracy of the
    information, data, analysis, discussions, recommendations, and conclusions
    presented herein. The contents do not necessarily reflect the views,
    opinions, endorsements, or policies of UDOT or the U.S. Department of Transportation. 
keywords: 
  - Temporary Portable Rumble Strips
  - Work Zone Safety
  - Driver Attention


bibliography: 
  - references.bib
  - extra_refs.yaml
cite-method: citeproc
csl: american-society-of-civil-engineers.csl

format:
  html:
    theme: cosmo
  elsevier-pdf:
    include-in-header: 
      - packages.tex
    fontsize: 12pt
    journal:
      name: ASCE 2027
    keep-tex: true
    top-level-division: section
    toc: false

